#!/usr/bin/python
import pymysql
from datetime import datetime
from pytz import timezone
import re
import pytz
import sys
import email
import smtplib
import socket
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage

#db = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='XXXXXXXXXX', db='expo_nova')
full_msg = sys.stdin.readlines()

msg = email.message_from_string(''.join(full_msg))

to = msg['to']
froma = msg['from']
subject = msg['subject']
subject_concat = msg['subject'].replace('\n', '')
body = msg['body']


if re.findall("LA region under project",subject_concat) :
  mysql_host='controllerla'
else:
  mysql_host='controller'
db = pymysql.connect(host=mysql_host, port=3306, user='expostack', passwd='XXXXXX', db='expo_manila')
print "Controller Name: " + mysql_host

def notify(receiver, sharename, flavor, whattodo,ipaddress,submitter):
    me = "expostack@mydomain.com"
    msg = MIMEMultipart('related')
    msgAlternative = MIMEMultipart('alternative')
    receiversplit = receiver.split("@")
    if len(receiversplit)==2:
       aaaa=""
    else:
       receiver = "cloudautomation@mydomain.com"
    msg['From'] = me
    you = receiver;
    msg['To'] = receiver;
    msg.preamble = 'This is a multi-part message in MIME format.'
    text = "Hi!"
    font = "<font face=verdana size=2>"
    if whattodo == "createrequeststart":
       msg['Subject'] = "Your request for Expostack Share " + sharename + "" + " is submitted"
       html1 = "<html><head></head><body>" + font + "<b>Share Name  : </b>" + sharename + "<br><b>flavor : </b>" + flavor + "<br><br> <b>Thanks and Regards</b><br>Expostack Administrator"

    if whattodo == "deleterequeststart":
       msg['Subject'] = "Your request for Expostack Share " + sharename + "" + " destroy has been submitted"
       html1 = "<html><head></head><body>" + font + "<b>Share Name  : </b>" + sharename + "<br><b>Submitted By</b> :" + submitter + "<br><b> Thanks and Regards</b><br>Expostack Administrator"

    if whattodo == "extendlease":
       msg['Subject'] = "Lease of Expostack Share " + sharename + " is extended successfully by " + flavor + ""
       html1 = "<html><head></head><body><pre>Lease for Share Name  : " + sharename + " is extended successfully by " + flavor +                                          "<br><br>If you have any questions / issues to renew VM. Please open" +             " Helpdesk Ticket to noc@mydomain.com.<br><br>Regards,<br>Expo Stack Administrator</pre>"

    htmlfinal = []
    htmlb = ''.join(htmlfinal)
    html = ''.join(str(x) for x in (html1,htmlb))
    part1 = MIMEText(text, 'plain')
    part2 = MIMEText(html, 'html')
    msg.attach(msgAlternative)
    msgAlternative.attach(part1)
    msgAlternative.attach(part2)
    s = smtplib.SMTP('mail.mydomain.com')
    s.sendmail(me, you, msg.as_string())
    s.quit()


if froma == "":
   print "Send to spam"
else:
   if "RE: Reminder: Share Name" in subject or "Re: Reminder: Share Name" in subject:
      stringsplit = subject.split(' ');
      share = stringsplit[4];
      share_id = re.findall("\((.*?)\)", share)
      shareid = share_id[0]
      howmany = stringsplit[17];
      sharename = share.split('(')
      sql = "select owner,sharename from lease_active_shares where shareuuid='"+shareid+"'"
      cursor = db.cursor()
      cursor.execute(sql)
      resultnew = cursor.fetchall()
      for rows in resultnew:
          userowner = rows[0] 
          sharename = rows[1]
          if userowner == "":
             print "Owner not found";
          else:
             date_format='%Y-%m-%d %H:%M:%S'
             datez = datetime.now(tz=pytz.utc)
             currentdate = datetime.strftime(datez, date_format);

             if "d" in howmany:
                howmanysplit1 = howmany.split('d')
                howmanysplit = howmanysplit1[0].split('+')
                sql = "update lease_active_shares set created_on='"+currentdate+"',leasedays="+howmanysplit[1]+",requesttype='days' where shareuuid='"+shareid+"'"
                print sql
                if int(howmanysplit[1]) > 60:
                   sql = "update lease_active_shares set created_on='"+currentdate+"',leasedays=60,requesttype='days' where shareuuid='"+shareid+"'"
                cursor.execute(sql)
                print "AMan " + str(userowner) + " " + str(sharename) + " " + str(howmany)
                db.commit()
                if int(howmanysplit[1]) > 60:
                  notify(userowner,share,60,"extendlease","nil","nil")
                  notify("suhaib.chishti@mydomain.com",share,60,"extendlease","nil","nil")
                  notify("cloudautomation@mydomain.com",share,60,"extendlease","nil","nil")
                else:
                  notify(userowner,share,howmany,"extendlease","nil","nil") 
                  notify("suhaib.chishti@mydomain.com",share,howmany,"extendlease","nil","nil") 
                  notify("cloudautomation@mydomain.com",share,howmany,"extendlease","nil","nil")

             if "h" in howmany:
                howmanysplit1 = howmany.split('h')
                howmanysplit = howmanysplit1[0].split('+')
                sql = "update lease_active_shares set created_on='"+currentdate+"',leasedays="+howmanysplit[1]+",requesttype='hours' where shareuuid='"+shareid+"'"
                if int(howmanysplit[1]) > 1440:
                   sql = "update lease_active_shares set created_on='"+currentdate+"',leasedays=60,requesttype='days' where shareuuid='"+shareid+"'"
                cursor.execute(sql)
                db.commit()
                if int(howmanysplit[1]) > 1440:
		   notify(userowner,share,60,"extendlease","nil","nil")
                   notify("suhaib.chishti@mydomain.com",share,60,"extendlease","nil","nil")
                   notify("cloudautomation@mydomain.com",share,60,"extendlease","nil","nil")
                else:
                   notify(userowner,share,howmany,"extendlease","nil","nil")
                   notify("suhaib.chishti@mydomain.com",share,howmany,"extendlease","nil","nil")
                   notify("cloudautomation@mydomain.com",share,howmany,"extendlease","nil","nil")
		  

   if "Create Share" in subject or "create share" in subject:
      stringsplit = subject.split(' ');
      share = stringsplit[2];
      howmany = stringsplit[3];
      ownername = stringsplit[4];
      size = stringsplit[5];
      sharename = share.split('.')
      cursor = db.cursor()
      checkexist = "select * from lease_active_shares where hostname='" + hostname + "'"
      cursor.execute(checkexist)
      print "AMan Create " + str(hostname) + " " + str(howmany) + " " + str(ownername)
      if cursor.rowcount == 0:
         checkleaseinfo = "select * from leaseinfo where sharename='" + hostname + "'"
         cursor.execute(checkleaseinfo)

         if cursor.rowcount == 0:
           #sql = "insert into leaseinfo values ('','" + hostname + "','" + howmany + "')";
	   print ('Insert into sql')
         else:
	   print ('Update into sql')
           #sql = "update leaseinfo set leasedays='" + howmany + "' where sharename='" + hostname + "'"

         cursor.execute(sql)
         db.commit()
         db.close()
        #notify(ownername,hostname,flavor,"createrequeststart","nil","nil")
