apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: expodockerregistry.tf-net.tribalfusion.com/itops/suhaib_repo:haproxy
      imagePullSecrets:
      - name: regsecret
